CHOOSEN_STOCKS = [
    "MRNA - Moderna",
    "CVX - Chevron",
    "CAT - Caterpillar",
    "GOOGL - Alphabet A",
    "COP - ConocoPhillips",
    "MA - Mastercard"
]

OIL_GAS_STOCKS = [
    "CVX - Chevron",
    "XOM - Exxon Mobil",
    "COP - ConocoPhillips",
    "OXY - Occidental",
    "HAL - Halliburton"
]

TECH_STOCKS = [
    "COIN - Coinbase Global",
    "INTC - Intel",
    "MSFT - Microsoft",
    "EBAY - eBay",
    "DELL - Dell Technologies",
    "CSCO - Cisco",
    "ORCL - Oracle",
    "MSI - Motorola Solutions",
    "ADSK - Autodesk",
    "GOOGL - Alphabet A",
    "ADBE - Adobe",
    "QCOM - Qualcomm",
    "AMAT - Applied Materials",
    "CDNS - Cadence Design",
    "MCHP - Microchip",
    "AAPL - Apple",
    "NTAP - NetApp",
    "LRCX - Lam Research",
    "INTU - Intuit",
    "CTSH - Cognizant A",
    "AKAM - Akamai",
    "KLAC - KLA Corp",
    "JNPR - Juniper",
    "EA - Electronic Arts",
    "GEN - Gen Digital",
    "NVDA - NVIDIA",
    "LRCX - Lam Research",
    "INTU - Intuit",
    "CTSH - Cognizant A",
    "AKAM - Akamai",
    "KLAC - KLA Corp",
    "JNPR - Juniper",
    "EA - Electronic Arts",
    "GEN - Gen Digital",
    "ADI - Analog Devices",
    "ACN - Accenture",
    "MU - Micron",
    "WDC - Western Digital",
    "IBM - IBM",
    "SPGI - S&P Global",
    "JBL - Jabil Circuit",
    "TXN - Texas Instruments",
    "HPQ - HP Inc",
    "HON - Honeywell",
    "AMD - AMD",
    "CRM - Salesforce Inc",
    "TER - Teradyne",
    "STX - Seagate",
    "A - Agilent Technologies",
    "NFLX - Netflix",
    "EQIX - Equinix",
    "FFIV - F5 Networks",
    "APH - Amphenol",
    "ROP - Roper Technologies",
    "AVGO - Broadcom",
    "NXPI - NXP",
    "TSLA - Tesla",
    "TTWO - Take-Two",
    "ANSS - ANSYS",
    "CHTR - Charter Communications",
    "CSGP - CoStar",
    "DXCM - DexCom",
    "FTNT - Fortinet",
    "IDXX - IDEXX Labs",
    "JKHY - Jack Henry & Associates",
    "MKTX - MarketAxess",
    "MPWR - Monolithic",
    "ON - ON Semiconductor",
    "PTC - PTC",
    "SMCI - Super Micro Computer",
    "ZBRA - Zebra",
    "TEL - TE Connectivity",
    "DLR - Digital Realty",
    "TDY - Teledyne Technologies",
    "TYL - Tyler Technologies",
    "META - Meta Platforms",
    "ENPH - Enphase",
    "APTV - Aptiv",
    "EPAM - EPAM Systems",
    "SWKS - Skyworks",
    "IT - Gartner",
    "SNPS - Synopsys",
    "NOW - ServiceNow Inc",
    "PANW - Palo Alto Networks",
    "CDW - CDW Corp",
    "GOOG - Alphabet C",
    "PAYC - Paycom Soft",
    "ANET - Arista Networks",
    "KEYS - Keysight Technologies",
    "QRVO - Qorvo Inc",
    "GDDY - Godaddy Inc",
    "PYPL - PayPal",
    "HPE - Hewlett Packard",
    "MTCH - Match Group",
    "CRWD - CrowdStrike Holdings",
    "PLTR - Palantir",
    "ABNB - Airbnb",
]

SNP500 = [
    "BA - Boeing",
    "COIN - Coinbase Global",
    "GM - General Motors",
    "CVX - Chevron",
    "C - Citigroup",
    "BAC - Bank of America",
    "T - AT&T",
    "CAT - Caterpillar",
    "INTC - Intel",
    "MSFT - Microsoft",
    "F - Ford Motor",
    "EBAY - eBay",
    "DELL - Dell Tech",
    "DIS - Walt Disney",
    "DOW - Dow",
    "CSCO - Cisco",
    "DE - Deere&Company",
    "FDX - FedEx",
    "GIS - General Mills",
    "GLW - Corning",
    "GS - Goldman Sachs",
    "JPM - JPMorgan",
    "KMB - Kimberly-Clark",
    "KHC - Kraft Heinz",
    "KO - Coca-Cola",
    "MCD - McDonald’s",
    "LLY - Eli Lilly",
    "ORCL - Oracle",
    "MRK - Merck&Co",
    "MSI - Motorola",
    "MMM - 3M",
    "VRTX - Vertex",
    "MNST - Monster Beverage",
    "FITB - Fifth Third",
    "CTAS - Cintas",
    "ADSK - Autodesk",
    "GILD - Gilead",
    "GOOGL - Alphabet A",
    "FI - Fiserv",
    "ADBE - Adobe",
    "QCOM - Qualcomm",
    "WBD - Warner Bros Discovery",
    "AMAT - Applied Materials",
    "STLD - Steel Dynamics",
    "CDNS - Cadence Design",
    "MCHP - Microchip",
    "WYNN - Wynn Resorts",
    "ISRG - Intuitive Surgical",
    "NDAQ - Nasdaq Inc",
    "HSIC - Henry Schein",
    "PAYX - Paychex",
    "VRSN - VeriSign",
    "AAPL - Apple",
    "FAST - Fastenal",
    "NTRS - Northern Trust",
    "CHRW - CH Robinson",
    "PCAR - PACCAR",
    "AMZN - Amazon.com",
    "ROST - Ross Stores",
    "NTAP - NetApp",
    "GRMN - Garmin",
    "COST - Costco",
    "LRCX - Lam Research",
    "INTU - Intuit",
    "EXPE - Expedia",
    "CTSH - Cognizant A",
    "AKAM - Akamai",
    "KLAC - KLA Corp",
    "JNPR - Juniper",
    "AMGN - Amgen",
    "EXPD - Expeditors Washington",
    "EA - Electronic Arts",
    "TROW - T Rowe",
    "BIIB - Biogen",
    "SCHW - Charles Schwab",
    "HBAN - Huntington Bancshares",
    "GEN - Gen Digital",
    "NVDA - NVIDIA",
    "SBUX - Starbucks",
    "CINF - Cincinnati Financial",
    "AXON - Axon Enterprise",
    "HOLX - Hologic",
    "CMCSA - Comcast",
    "MDT - Medtronic",
    "DOV - Dover",
    "NOC - Northrop Grumman",
    "MGM - MGM",
    "MA - Mastercard",
    "GD - General Dynamics",
    "DTE - DTE Energy",
    "ADI - Analog Devices",
    "CAH - Cardinal Health",
    "XEL - Xcel Energy",
    "DHI - DR Horton",
    "IPG - IPG",
    "LMT - Lockheed Martin",
    "WAT - Waters",
    "ACN - Accenture",
    "D - Dominion Energy",
    "XOM - Exxon Mobil",
    "CI - Cigna",
    "PEG - Public Service Enterprise",
    "NI - NiSource",
    "ZBH - Zimmer Biomet",
    "CSX - CSX",
    "ICE - ICE",
    "LUV - Southwest Airlines",
    "ITW - Illinois Tool Works",
    "DRI - Darden Restaurants",
    "TFC - Truist Financial Corp",
    "HAL - Halliburton",
    "PLD - Prologis",
    "MKC - McCormick&Co",
    "HST - Host Hotels Resorts",
    "EL - Estee Lauder",
    "IP - International Paper",
    "EMR - Emerson",
    "CLX - Clorox",
    "COP - ConocoPhillips",
    "CL - Colgate-Palmolive",
    "PNW - Pinnacle West",
    "RF - Regions Financial",
    "CNP - CenterPoint Energy",
    "MET - MetLife",
    "EXC - Exelon",
    "BAX - Baxter",
    "OXY - Occidental",
    "SO - Southern",
    "TPR - Tapestry",
    "LEN - Lennar",
    "CPB - Campbell Soup",
    "STT - State Street",
    "PGR - Progressive",
    "VMC - Vulcan Materials",
    "PH - Parker-Hannifin",
    "GPC - Genuine Parts",
    "CBRE - CBRE A",
    "DD - DuPont De Nemours",
    "SHW - Sherwin-Williams",
    "PFE - Pfizer",
    "WFC - Wells Fargo&Co",
    "WMT - Walmart",
    "EIX - Edison",
    "SNA - Snap-On",
    "EFX - Equifax",
    "MCK - McKesson",
    "ETR - Entergy",
    "CMS - CMS Energy",
    "AMP - Ameriprise Financial",
    "AIG - AIG",
    "RL - Ralph Lauren A",
    "IFF - IFF",
    "GWW - WW Grainger",
    "STZ - Constellation Brands A",
    "AMT - American Tower",
    "PM - Philip Morris",
    "FIS - Fidelity National Info",
    "MO - Altria",
    "BALL - Ball",
    "HIG - Hartford",
    "HSY - Hershey Co",
    "MS - Morgan Stanley",
    "PNC - PNC Financial",
    "WM - Waste Management",
    "COR - Cencora Inc",
    "AIZ - Assurant",
    "KR - Kroger",
    "TAP - Molson Coors Brewing B",
    "HD - Home Depot",
    "BDX - Becton Dickinson",
    "SJM - JM Smucker",
    "BBY - Best Buy",
    "ADM - Archer-Daniels-Midland",
    "BFb - Brown Forman",
    "IBM - IBM",
    "UNP - Union Pacific",
    "MU - Micron",
    "AVY - Avery Dennison",
    "MRO - Marathon Oil",
    "CF - CF Industries",
    "APA - APA Corp",
    "DUK - Duke Energy",
    "KEY - KeyCorp",
    "LH - Labcorp Holdings",
    "BXP - BXP Inc",
    "WDC - Western Digital",
    "PPG - PPG Industries",
    "SPGI - S&P Global",
    "WMB - Williams",
    "ELV - Elevance Health",
    "J - Jacobs Engineering",
    "EMN - Eastman Chemical",
    "VZ - Verizon",
    "NUE - Nucor",
    "OMC - Omnicom",
    "AVB - AvalonBay",
    "MAR - Marriott Int",
    "IR - Ingersoll Rand",
    "BMY - Bristol-Myers Squibb",
    "AEP - American Electric Power",
    "TMO - Thermo Fisher Scientific",
    "NEM - Newmont Goldcorp",
    "PSA - Public Storage",
    "TRV - Travelers",
    "SWK - Stanley Black Decker",
    "BEN - Franklin Resources",
    "HUM - Humana",
    "PARA - Paramount Global B",
    "CB - Chubb",
    "JNJ - J&J",
    "TSN - Tyson Foods",
    "TGT - Target",
    "JBL - Jabil Circuit",
    "AXP - American Express",
    "MAS - Masco",
    "SYK - Stryker",
    "DFS - Discover",
    "PRU - Prudential Financial",
    "ABT - Abbott Labs",
    "GE - GE Aerospace",
    "DGX - Quest Diagnostics",
    "UPS - United Parcel Service",
    "CVS - CVS Health Corp",
    "PPL - PPL",
    "SPG - Simon Property",
    "JCI - Johnson Controls",
    "CMI - Cummins",
    "ALL - Allstate",
    "SRE - Sempra Energy",
    "DVN - Devon Energy",
    "CAG - Conagra Brands",
    "TJX - TJX",
    "FE - FirstEnergy",
    "GL - Globe Life",
    "RTX - Rtx Corp",
    "PHM - PulteGroup",
    "VLO - Valero Energy",
    "BSX - Boston Scientific",
    "COF - Capital One Financial",
    "PCG - PG E",
    "NSC - Norfolk Southern",
    "AFL - Aflac",
    "EQR - Equity Residential",
    "APD - Air Products",
    "PFG - Principal Financial",
    "TXN - Texas Instruments",
    "HPQ - HP Inc",
    "HON - Honeywell",
    "AMD - AMD",
    "MTB - M&T Bank",
    "MOS - Mosaic",
    "RVTY - Revvity",
    "LVS - Las Vegas Sands",
    "FCX - Freeport-McMoran",
    "AZO - AutoZone",
    "SYY - Sysco",
    "AEE - Ameren",
    "ETN - Eaton",
    "CRM - Salesforce Inc",
    "ED - Consolidated Edison",
    "AES - The AES",
    "TXT - Textron",
    "USB - U.S. Bancorp",
    "V - Visa A",
    "BKR - Baker Hughes",
    "HES - Hess",
    "YUM - Yum! Brands",
    "MMC - Marsh McLennan",
    "K - Kellanova",
    "KIM - Kimco Realty",
    "ECL - Ecolab",
    "EOG - EOG Resources",
    "AON - Aon",
    "HAS - Hasbro",
    "BK - Bank of NY Mellon",
    "SLB - Schlumberger",
    "WBA - Walgreens Boots",
    "ROK - Rockwell Automation",
    "PEP - PepsiCo",
    "UNH - UnitedHealth",
    "TER - Teradyne",
    "DHR - Danaher",
    "STX - Seagate",
    "A - Agilent Technologies",
    "DAL - Delta Air Lines",
    "MCO - Moody’s",
    "NKE - Nike",
    "PG - P&G",
    "WY - Weyerhaeuser",
    "ADP - ADP",
    "KDP - Keurig Dr Pepper",
    "LOW - Lowe’s",
    "UAL - United Airlines Holdings",
    "NFLX - Netflix",
    "NWS - News Corp",
    "EQIX - Equinix",
    "BKNG - Booking",
    "ORLY - O’Reilly Automotive",
    "BLK - BlackRock",
    "CME - CME Group",
    "JBHT - JB Hunt",
    "L - Loews",
    "NEE - NextEra Energy",
    "FSLR - First Solar",
    "VTRS - Viatris",
    "FFIV - F5 Networks",
    "EW - Edwards Lifesciences",
    "NWSA - News Corp A",
    "APH - Amphenol",
    "BRKb - Berkshire Hathaway B",
    "CTRA - Coterra Energy",
    "KMX - CarMax",
    "CMG - Chipotle Mexican Grill",
    "DVA - DaVita",
    "EQT - EQT",
    "FMC - FMC",
    "LHX - L3Harris Technologies",
    "DOC - Healthpeak Properties",
    "WELL - Welltower",
    "HRL - Hormel Foods",
    "IVZ - Invesco",
    "IRM - Iron Mountain",
    "ES - Eversource Energy",
    "NRG - NRG",
    "OKE - ONEOK",
    "RSG - Republic Services",
    "ROP - Roper Technologies",
    "VTR - Ventas",
    "WEC - WEC Energy",
    "BX - Blackstone",
    "MPC - Marathon Petroleum",
    "AVGO - Broadcom",
    "NXPI - NXP",
    "TSLA - Tesla",
    "TTWO - Take-Two",
    "DLTR - Dollar Tree",
    "ALGN - Align",
    "ANSS - ANSYS",
    "BLDR - Builders FirstSource",
    "CHTR - Charter Communications",
    "CSGP - CoStar",
    "DXCM - DexCom",
    "ERIE - Erie Indemnity",
    "FTNT - Fortinet",
    "IDXX - IDEXX Labs",
    "INCY - Incyte",
    "JKHY - Jack Henry&Associates",
    "MKTX - MarketAxesss",
    "MPWR - Monolithic",
    "NDSN - Nordson",
    "ON - ON Semiconductor",
    "PTC - PTC",
    "PODD - Insulet",
    "POOL - Pool",
    "SMCI - Super Micro Computer",
    "TECH - Bio-Techne",
    "ZBRA - Zebra",
    "BWA - BorgWarner",
    "TMUS - T-Mobile US",
    "PWR - Quanta Services",
    "LDOS - Leidos",
    "TEL - TE Connectivity",
    "MAA - Mid-America Apartment",
    "CRL - Charles River Laboratories",
    "HII - Huntington Ingalls Industries",
    "MTD - Mettler-Toledo",
    "FRT - Federal Realty",
    "LYV - Live Nation Entertainment",
    "MLM - Martin Marietta Materials",
    "FDS - FactSet Research",
    "RJF - Raymond James Financial",
    "DLR - Digital",
    "ESS - Essex Property",
    "FICO - Fair Isaac",
    "COO - Cooper",
    "MOH - Molina Healthcare",
    "EG - Everest",
    "REG - Regency Centers",
    "DG - Dollar General",
    "TDG - Transdigm",
    "ATO - Atmos Energy",
    "BRO - Brown&Brown",
    "DPZ - Domino’s Pizza Inc",
    "HCA - HCA",
    "HUBB - Hubbell",
    "ROL - Rollins",
    "STE - STERIS",
    "RMD - ResMed",
    "MSCI - MSCI",
    "NVR - NVR",
    "CCL - Carnival Corp",
    "WST - West Pharmaceutical Services",
    "TDY - Teledyne Technologies",
    "TYL - Tyler Technologies",
    "TRGP - Targa Resources",
    "META - Meta Platforms",
    "ARE - Alexandria RE",
    "TFX - Teleflex",
    "WAB - Westinghouse Air Brake",
    "EVRG - Evergy",
    "WTW - Willis Towers Watson",
    "CZR - Caesars",
    "ENPH - Enphase",
    "APTV - Aptiv",
    "CCI - Crown Castle",
    "EPAM - EPAM Systems",
    "PNR - Pentair",
    "MDLZ - Mondelez",
    "SWKS - Skyworks",
    "TSCO - Tractor Supply",
    "DECK - Deckers Outdoor",
    "LULU - Lululemon Athletica",
    "REGN - Regeneron Pharma",
    "URI - United Rentals",
    "KMI - Kinder Morgan",
    "ALB - Albemarle",
    "CNC - Centene",
    "PSX - Phillips 66",
    "XYL - Xylem",
    "UDR - UDR",
    "SBAC - SBA Communications",
    "IT - Gartner",
    "IEX - IDEX",
    "UHS - Universal Health Services",
    "LKQ - LKQ",
    "BR - Broadridge",
    "EXR - Extra Space Storage",
    "CPT - Camden Property",
    "MHK - Mohawk Industries",
    "AWK - American Water Works",
    "LNT - Alliant Energy",
    "CE - Celanese",
    "BG - Bunge",
    "AME - Ametek",
    "WRB - WR Berkley",
    "LYB - LyondellBasell Industries",
    "RCL - Royal Caribbean Cruises",
    "CPAY - Corpay",
    "PKG - Packaging America",
    "AJG - Arthur J Gallagher",
    "CHD - Church&Dwight",
    "GNRC - Generac",
    "GPN - Global Payments",
    "O - Realty Income",
    "AOS - AO Smith",
    "ACGL - Arch Capital",
    "CBOE - Cboe Global",
    "CPRT - Copart",
    "ODFL - Old Dominion Freight Line",
    "SNPS - Synopsys",
    "TRMB - Trimble",
    "ULTA - Ulta Beauty",
    "VRSK - Verisk",
    "ABBV - AbbVie",
    "FANG - Diamondback",
    "NCLH - Norwegian Cruise Line",
    "ZTS - Zoetis Inc",
    "IQV - IQVIA Holdings",
    "NOW - ServiceNow Inc",
    "PANW - Palo Alto Networks",
    "KKR - KKR & Co",
    "CDW - CDW Corp",
    "HLT - Hilton Worldwide",
    "ALLE - Allegion PLC",
    "GOOG - Alphabet C",
    "PAYC - Paycom Soft",
    "ANET - Arista Networks",
    "SYF - Synchrony Financial",
    "CTLT - Catalent Inc",
    "CFG - Citizens Financial Group Inc",
    "KEYS - Keysight Technologies",
    "QRVO - Qorvo Inc",
    "GDDY - Godaddy Inc",
    "PYPL - PayPal",
    "HPE - Hewlett Packard",
    "MTCH - Match Group",
    "FTV - Fortive",
    "LW - Lamb Weston Holdings",
    "INVH - Invitation Homes",
    "VST - Vistra Energy",
    "VICI - VICI Properties",
    "DAY - Dayforce",
    "MRNA - Moderna",
    "UBER - Uber Tech",
    "FOXA - Fox Corp A",
    "FOX - Fox Corp B",
    "CRWD - CrowdStrike Holdings",
    "CTVA - Corteva",
    "AMCR - Amcor PLC",
    "TT - Trane Technologies",
    "OTIS - Otis Worldwide",
    "CARR - Carrier Global",
    "HWM - Howmet",
    "PLTR - Palantir",
    "ABNB - Airbnb",
    "CEG - Constellation Energy",
    "GEHC - GE HealthCare",
    "KVUE - Kenvue",
    "VLTO - Veralto",
    "LIN - Linde PLC",
    "GEV - GE Vernova LLC",
    "SOLV - Solventum",
    "AMTM - Amentum Holdings LLC",
]
